// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA3DEcco7GKAiDgnEXczJBumAV9MeBOqc',
    appId: '1:168913331292:web:05d620bd6e75a99a2f7299',
    messagingSenderId: '168913331292',
    projectId: 'rkh-gedunga',
    authDomain: 'rkh-gedunga.firebaseapp.com',
    storageBucket: 'rkh-gedunga.firebasestorage.app',
    measurementId: 'G-C5NRGBXX7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCebWoEnf7756azBAS9-dKxe_O8WyE-io',
    appId: '1:168913331292:android:3870d924c7a100ac2f7299',
    messagingSenderId: '168913331292',
    projectId: 'rkh-gedunga',
    storageBucket: 'rkh-gedunga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFc6XAV7kjTKbMMxVcCizB8exuEaFmEI',
    appId: '1:168913331292:ios:d0e465cfc316f6872f7299',
    messagingSenderId: '168913331292',
    projectId: 'rkh-gedunga',
    storageBucket: 'rkh-gedunga.firebasestorage.app',
    iosBundleId: 'com.example.rkhGeda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFc6XAV7kjTKbMMxVcCizB8exuEaFmEI',
    appId: '1:168913331292:ios:d0e465cfc316f6872f7299',
    messagingSenderId: '168913331292',
    projectId: 'rkh-gedunga',
    storageBucket: 'rkh-gedunga.firebasestorage.app',
    iosBundleId: 'com.example.rkhGeda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA3DEcco7GKAiDgnEXczJBumAV9MeBOqc',
    appId: '1:168913331292:web:6b44ca84972049252f7299',
    messagingSenderId: '168913331292',
    projectId: 'rkh-gedunga',
    authDomain: 'rkh-gedunga.firebaseapp.com',
    storageBucket: 'rkh-gedunga.firebasestorage.app',
    measurementId: 'G-RFK4K8Z62N',
  );
}
